### ISSUE TITLE
Merchant

### ISSUE THREAD

**Issue by Issacar13** [tianevitt/tianzes-otari-extras#10]
I think there should be the option to use Monk's better journal "shop" page instead of the actor merchant. It is more in depth (You can choose opening hours, it has a log of what the vendor sold/bought) and when open the vendors through the Otari Market journal while using Monk Better Journal it breaks the vendors.

I really like this module, it adds a nice layer to the town. Thank you for sharing it!

**Comment by tianevitt** [comment]
Believe me, I understand the reason for this request. I used to love Monk's Enhanced Journals myself, and I was a Monk's Shops power user, but I made the painful decision to stop using it after the last Foundry update, because I was without my journals for about six weeks. (Yes, I should have waited before updating.)

Since these shops are merchant actors, they are, as you discovered, completely incompatible with Monk's journal-based shops. However, what I maybe could do is create some roll tables to populate the items in Monk's Shops. I'll spin up another test world with Monk's Enhanced Journals installed and give it a try, and maybe include both kinds of shops in my next release.

I have completely transitioned to using the Shop feature in Item Piles. I believe it has all the features from the Enhanced Journal shops, and it works very well. I almost included it as a dependency, but decided that would be too intrusive.

Anyway, thanks for the suggestion, and I am glad you are enjoying this mod. I have another map ready for the next release, for the Fish Camp Base from Troubles in Otari.

**Comment by tianevitt** [comment]
Added with 1.2.0. See the new compendium pack with the shops, and also a journal in the main module folder explains what I did. Thanks!

**Comment by Issacar13** [comment]
That's amazing! You did it so fast! Thanks alot, You're adding alot of depth to this area. Golarion needs more content creators like you :D

**Comment by Issacar13** [comment]
I have also been fiddling with replacing the Actor token by a tile, but I'm not sure if I like that idea


"I have completely transitioned to using the Shop feature in Item Piles. I believe it has all the features from the Enhanced Journal shops, and it works very well. I almost included it as a dependency, but decided that would be too intrusive."

The work around for this would be to offer 2 version of the market map in the compendium, one with the original actor token and one with the MEJ shops. GM can choose whichever version they prefer this way for their campaign. If you want me to update tan Otari scene with MEJ tile updated I can send it sometimes over the weekend if it can save you some time to work on other things

**Comment by tianevitt** [comment]
Did you try setting the merchant actor permissions to "none"? The details are in the Shop Journals and Rolltables journal. I think it would work much better than a tile, which you cannot interact with.

Your idea for an additional scene is a pretty good one. I am not sure what you have in mind for the original actor token for the MEJ version of the scene. So if you do export the json of a map that you did this for, I'd be very curious to take a look.

And thank you! Working on this is helping me get through an illness.

**Comment by Issacar13** [comment]
[fvtt-Scene-otari-market-square-(MEJ-Version).json](https://github.com/tianevitt/tianzes-otari-extras/files/15286021/fvtt-Scene-otari-market-square-.MEJ-Version.json)
Oh I missed that note, yes your instructions to set the map are pretty straightforward and that's what I did in the end. The only thing I had t oadd was the map note for Lathenar's shop, I included the json file of the map in this message too

<img width="148" alt="image" src="https://github.com/tianevitt/tianzes-otari-extras/assets/168503811/72c93279-5f69-4c4d-979f-bdb3630726cc">

My original thinking with the tiled version of the actors was that it would also allow me to link the beginner's box journal page, but after thought it would just be some kind of redundancy information since your description are more detailed then what the module provides.
